#! /bin/sh

# startup commands

sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         2
bspc config window_gap           5 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 any

bspc rule -a Soffice state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Code desktop='^2'
bspc rule -a discord desktop='^4'


# wifi and bluetooth tray
nm-applet &
blueman-applet &

# wallpaper, polybar, compositor
dyWall.py &
nitrogen --restore &
compton &
redshift -O 4500 &
/home/dak-x/.config/polybar/launch.sh --blocks &
# hack for using gnome themes and other settings
/usr/lib/gnome-settings-daemon/gsd-xsettings &

# set capslock -> ctrl 
setxkbmap -layout us -option ctrl:nocaps &
